# Generated by Django 5.1.15 on 2026-06-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_rename_instagram_personal_to_login'),
        ('organizations', '0002_organization_billing_email'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformcredential',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='platformcredential',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace-scoped override. NULL = org-level credential.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_credentials', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='platformcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('organization', 'platform'), name='unique_org_platform_null_workspace'),
        ),
        migrations.AddConstraint(
            model_name='platformcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'platform'), name='unique_workspace_platform'),
        ),
    ]
