# Generated by Django 5.1.15 on 2026-06-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_alter_workspace_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="integration_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
