# Generated by Django 5.1.15 on 2026-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='integration_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-workspace integration keys (e.g., unsplash_access_key).'),
        ),
    ]
