# Generated by Django 5.1.15 on 2026-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0002_mediaasset_is_starred_mediaasset_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External ID from stock photo provider (e.g., Unsplash photo ID)",
                max_length=100,
            ),
        ),
    ]
