# Generated by Django 5.1.15 on 2026-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_is_starred_mediaasset_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
